FROM nvcr.io/nvidia/isaac-sim:2022.2.0
LABEL dev.containers.features="common"

ENV ROS_DISTRO=humble
ENV ROS_PYTHON_VERSION=3
ENV DEBIAN_FRONTEND=noninteractive

# COPY install-ros-humble.sh .

# RUN ls